resources:
  - loki/loki-config.yaml
  - loki/loki-deployment.yaml
  - loki/loki-service.yaml
  - promtail/promtail-daemonset.yaml
  - promtail/promtail-config.yaml
  - hello/hello-deployment.yaml
  - hello/hello-service.yaml