storage:
  engine: "filesystem"
  filesystem:
    directory: "/loki/data"
  
schema_config:
  configs:
    - from: 2020-10-22
      store: "filesystem"
      schema: "v11"
      index:
        prefix: "index_"
        period: "168h"

limits_config:
  max_cache_size: 5000000000
  max_entries_limit: 5000000

compactor:
  working_directory: "/loki/compactor"
  retention_enabled: true
  retention_delete_delay: 24h

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

log_level: "info"