loki-poc/k8s/promtail/promtail-config.yaml

server:
  http:
    port: 9080
  grpc:
    port: 9095

positions:
  filename: /var/log/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log

  - job_name: hello
    static_configs:
      - targets:
          - localhost
        labels:
          job: hello
          __path__: /var/log/hello/*.log